### ISSUE TITLE
Layouts are broken with Svelte Kit

### ISSUE THREAD

**Issue by dkzlv** [pngwn/MDsveX#277]
**Describe the bug**
If you describe any layouts in mdsvex config, your app won't compile in SvelteKit at all. Says something about circular dependency between `generated/root.svelte` and `components/layout.svelte`.

**Logs**
<details>
  <summary>Logs from builder</summary>

```
  Circular dependency: //Users/dankozlov/Projects/temp/mdsvex-kit-repro/.svelte-kit/dev/generated/root.svelte -> /src/components/layout.svelte -> /src/components/layout.svelte
Cannot read property 'default' of null
TypeError: Cannot read property 'default' of null
    at layout.svelte:6:27
    at Object.$$render (/Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/svelte/internal/index.js:1555:22)
    at root.svelte:48:27
    at $$render (/Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/svelte/internal/index.js:1555:22)
    at Object.render (/Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/svelte/internal/index.js:1563:26)
    at render_response (file:///Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/@sveltejs/kit/dist/ssr.js:377:28)
    at async respond$1 (file:///Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/@sveltejs/kit/dist/ssr.js:1153:10)
    at async render_page (file:///Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/@sveltejs/kit/dist/ssr.js:1196:20)
    at async resolve (file:///Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/@sveltejs/kit/dist/ssr.js:1551:10)
    at async respond (file:///Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/@sveltejs/kit/dist/ssr.js:1524:10)
Cannot read property 'default' of null
TypeError: Cannot read property 'default' of null
    at layout.svelte:6:27
    at Object.$$render (/Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/svelte/internal/index.js:1555:22)
    at root.svelte:48:27
    at $$render (/Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/svelte/internal/index.js:1555:22)
    at Object.render (/Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/svelte/internal/index.js:1563:26)
    at render_response (file:///Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/@sveltejs/kit/dist/ssr.js:377:28)
    at async respond_with_error (file:///Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/@sveltejs/kit/dist/ssr.js:946:10)
    at async respond$1 (file:///Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/@sveltejs/kit/dist/ssr.js:1165:10)
    at async render_page (file:///Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/@sveltejs/kit/dist/ssr.js:1196:20)
    at async resolve (file:///Users/dankozlov/Projects/temp/mdsvex-kit-repro/node_modules/@sveltejs/kit/dist/ssr.js:1551:10)

...
```

</details>

**To Reproduce**

Here's a [repro](https://github.com/dkzlv/mdsvex-kit-repro).
But there's nothing there, really. Just a `.svx` in `routes` and a layout in `components`.

**Expected behavior**
Should work.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Memory: 86.83 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.120 
    svelte: ^3.34.0 => 3.38.3```

</details>

**Severity**
Since Kit is in beta, I guess it's not severe. But I consider it stable enough now, so probably should be fixed.

**Comment by iansoper** [comment]
I'm having a similar issue with layouts. When I define any layout other than the default `_` then i get this error in dev or build:

```
Unexpected token
ParseError: Unexpected token
    at error (/Users/iansoper/workspaces/iansopercom-svelte-kit/node_modules/svelte/compiler.js:17656:20)
    at Parser$1.error (/Users/iansoper/workspaces/iansopercom-svelte-kit/node_modules/svelte/compiler.js:17732:10)
    at Parser$1.acorn_error (/Users/iansoper/workspaces/iansopercom-svelte-kit/node_modules/svelte/compiler.js:17726:15)
    at Object.read_script [as read] (/Users/iansoper/workspaces/iansopercom-svelte-kit/node_modules/svelte/compiler.js:8461:17)
    at tag (/Users/iansoper/workspaces/iansopercom-svelte-kit/node_modules/svelte/compiler.js:16852:34)
    at new Parser$1 (/Users/iansoper/workspaces/iansopercom-svelte-kit/node_modules/svelte/compiler.js:17691:22)
    at Object.parse$3 [as parse] (/Users/iansoper/workspaces/iansopercom-svelte-kit/node_modules/svelte/compiler.js:17823:21)
    at process_layouts (/Users/iansoper/workspaces/iansopercom-svelte-kit/node_modules/mdsvex/dist/main.cjs.js:25908:26)
    at mdsvex (/Users/iansoper/workspaces/iansopercom-svelte-kit/node_modules/mdsvex/dist/main.cjs.js:26024:12)
    at file:///Users/iansoper/workspaces/iansopercom-svelte-kit/svelte.config.js:28:5
```
    
The error comes from the MDsvex config section in the `svelte.config.js` file. When I comment out the other layouts in the `mdsvex.config.js` file then  it builds with no errors.

**Comment by rohanrajpal** [comment]
A workaround is in this project, works fine I guess. Yet to experiment with all of the mdsvex features tho.

https://github.com/sharu725/hagura-sveltekit

**Comment by kmal-kenneth** [comment]
With similar problem here.

`svelte.config.js`

```javascript
import adapter from "@sveltejs/adapter-auto";
import preprocess from "svelte-preprocess";

import { mdsvex } from "mdsvex";
const mdsvexConfig = {
  extensions: [".svelte.md", ".md", ".svx"],

  layout: "./layouts/article.svelte",

  smartypants: {
    dashes: "oldschool",
  },

  remarkPlugins: [],
  rehypePlugins: [],
};

/** @type {import('@sveltejs/kit').Config} */
const config = {
  extensions: [".svelte", ...mdsvexConfig.extensions],

  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: [preprocess(), mdsvex(mdsvexConfig)],

  kit: {
    adapter: adapter(),

    // hydrate the <div id="svelte"> element in src/app.html
    target: "#svelte",
  },
};

export default config;
```

And the error message.

```shell
yarn run v1.22.17
warning package.json: No license field
$ svelte-kit dev
Colon is expected
ParseError: Colon is expected
    at error (/home/kenet/Proyectos/experimentos/my-app/node_modules/svelte/compiler.js:17703:20)
    at Parser$1.error (/home/kenet/Proyectos/experimentos/my-app/node_modules/svelte/compiler.js:17779:10)
    at Object.read_style [as read] (/home/kenet/Proyectos/experimentos/my-app/node_modules/svelte/compiler.js:14116:21)
    at tag (/home/kenet/Proyectos/experimentos/my-app/node_modules/svelte/compiler.js:16868:34)
    at new Parser$1 (/home/kenet/Proyectos/experimentos/my-app/node_modules/svelte/compiler.js:17738:22)
    at Object.parse$3 [as parse] (/home/kenet/Proyectos/experimentos/my-app/node_modules/svelte/compiler.js:17870:21)
    at process_layouts (/home/kenet/Proyectos/experimentos/my-app/node_modules/mdsvex/dist/main.cjs.js:25908:26)
    at mdsvex (/home/kenet/Proyectos/experimentos/my-app/node_modules/mdsvex/dist/main.cjs.js:26024:12)
    at file:///home/kenet/Proyectos/experimentos/my-app/svelte.config.js:24:30
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Looks like a sveltekit bug.

But I really don't know what is going on.

`package.json`

```json
{
  "name": "my-app",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "package": "svelte-kit package",
    "preview": "svelte-kit preview",
    "check": "svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-check --tsconfig ./tsconfig.json --watch"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "next",
    "@sveltejs/kit": "next",
    "@types/cookie": "^0.4.1",
    "mdsvex": "^0.9.8",
    "svelte": "^3.44.0",
    "svelte-check": "^2.2.6",
    "svelte-preprocess": "^4.9.4",
    "tslib": "^2.3.1",
    "typescript": "^4.4.3"
  },
  "type": "module",
  "dependencies": {
    "@fontsource/fira-mono": "^4.5.0",
    "@lukeed/uuid": "^2.0.0",
    "cookie": "^0.4.1"
  }
}
```

**Comment by jlarfors** [comment]
Something that has bitten me in two projects now is that mdsvex doesn't seem to support Typescript.

Make sure you are not using any `lang="ts"` in your `<script>` blocks in layouts. Hopefully this helps someone else arriving here because of this.

**Comment by kmal-kenneth** [comment]
ok my error

**Comment by deb85** [comment]
Remove `.svelte` from `msdvexConfig.extensions`.

Seems like msdvex is trying to render both the default +layout and the markdown layout, causing some sort of infinite loop. Just don't let msdvex render `.svelte` files, and the loop won't happen.
