### ISSUE TITLE
HTML character references throw "offset is longer than source length" error

### ISSUE THREAD

**Issue by vwkd** [pngwn/MDsveX#296]
## Description

When using HTML character references like `&lt;` in a MDsveX page with SvelteKit, Vite throws an `offset is longer than source length!` error.

## Reproduction

https://github.com/vwkd/sveltekit-bugs/tree/mdsvex-character-references

1. Run `npm run dev`
2. Observe error `offset is longer than source length!`

## System Info

```
  Binaries:
    Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.6.0/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.11 => 1.0.0-next.17 
    @sveltejs/kit: next => 1.0.0-next.158 
    mdsvex: ^0.9.8 => 0.9.8 
    svelte: ^3.34.0 => 3.42.3 
```

**Comment by vwkd** [comment]
I found some more failures. This time it's due to some LaTeX on a page, e.g.`$d_i \ldots d_0$`. This is obviously not supported by Markdown and I'm imagining remark throws an error. But it seems MDsveX doesn't pass the error on to the user and only much later in the chain the user sees this cryptic error message in Vite.

**Comment by milahu** [comment]
one problem is that vite throws these usless stack traces

```
Error: offset is longer than source length!
    at numberToPos (node_modules/vite/dist/node/chunks/dep-972722fa.js:4247:15)
    at formatError (node_modules/vite/dist/node/chunks/dep-972722fa.js:51169:24)
    at TransformContext.error (node_modules/vite/dist/node/chunks/dep-972722fa.js:51149:19)
    at Object.transform (node_modules/vite/dist/node/chunks/dep-972722fa.js:51357:25)
    at async transformRequest (node_modules/vite/dist/node/chunks/dep-972722fa.js:67098:29)
    at async instantiateModule (node_modules/vite/dist/node/chunks/dep-972722fa.js:73732:10)
```

with https://github.com/vitejs/vite/pull/4782 i get

```
formatError: error in numberToPos (Error: offset is longer than source length! offset 126 > length 48) while handling the error:
Expected valid tag name
4: </script>
5: 
6: <p>Lorem ipsum < dolor sit</p>
                   ^
ParseError: Expected valid tag name
    at error (node_modules/svelte/compiler.mjs:17698:19)
    at Parser$1.error (node_modules/svelte/compiler.mjs:17774:9)
    [...]
```

**Comment by milahu** [comment]
digging deeper

<details>

<summary>node_modules/mdsvex/dist/main.cjs.js</summary>

```js
// line 8722

        if (namedEntity) {
          entityCharacters = characters;
          entity = namedEntity;
        }

        // DEBUG
        console.log(`\n\nmdsvex cjs 8727: found entity in ${characters}. named ${namedEntity}. type ${type}`);
        //console.dir(new Error());

```

```js
// line 8815

      // Found it!
      // First eat the queued characters as normal text, then eat an entity.
      if (reference) {
        flush();

        prev = now();
        index = end - 1;
        column += end - start + 1;
        result.push(reference);

        // DEBUG
        console.log(`mdsvex cjs 8827: push reference ${reference}`);
```

</details>

output

```
mdsvex cjs 8727: found entity in lt. named <. type named
mdsvex cjs 8827: push reference <
```

where does this code come from? [lets ask github](https://github.com/search?q=%22First+eat+the+queued+characters+as+normal+text%2C+then+eat+an+entity.%22&type=code) - looks like [parse-entities](https://github.com/wooorm/parse-entities)
some traces later, this is called by <code>[remark-parse](https://github.com/remarkjs/remark/tree/main/packages/remark-parse).markdown</code>

so the problem is ...

```js
	const toMDAST = unified()
		.use(markdown) // HERE
```

workaround:

```js
	const toMDAST = unified()
		.use(escapeLtGt)
		.use(markdown)
```

`escapeLtGt` would replace

- `&lt;` with `&amp;lt;`
- `&gt;` with `&amp;gt;`

**Comment by milahu** [comment]
quickfix

```js
// cjs js line 8716

      if (terminated) {
        end++;

        namedEntity = type === name$1 ? decodeEntity_1(characters) : false;

        // QUICKFIX
        if (namedEntity == '<') namedEntity = '&lt;';
        if (namedEntity == '>') namedEntity = '&gt;';

        if (namedEntity) {
          entityCharacters = characters;
          entity = namedEntity;
        }
```

much faster than fixing all the dependencies : )
[how to apply with patch-package](https://github.com/milahu/sveltekit-bugs/commit/8a0b7eb8933a31606be817a7397810e75081a24f)

**Comment by pngwn** [comment]
Late coming to this but I don't think `<` or `>` are really supported in the underlying parsers, entities seem to be decoded when parsed.

I think there are two issues about this now, can you check to see if [this issue](https://github.com/pngwn/MDsveX/issues/301) is reporting the same problem?

**Comment by milahu** [comment]
> can you check to see if [this issue](https://github.com/pngwn/MDsveX/issues/301) is reporting the same problem?

yes, its a duplicate

source here

```md
Lorem ipsum &lt; dolor sit
```

source there

```md
A paragraph started with &lt;h2&gt; 
```

with my quickfix, this is correctly rendered as

```
A paragraph started with <h2>
```

**Comment by pngwn** [comment]
Thank you! 

In v1, I have a plan to make the use of `<`, `>` character entities unnecessary, supporting `<` and `>` directly in text. But the entity situation will be resolve when mdsvex moves to a different parser.

**Comment by pngwn** [comment]
This issue has more information, I'll close the other.

**Comment by milahu** [comment]
> when mdsvex moves to a different parser.

in the mean time, you could use patch-package to patch the dependency `remark-parse.markdown`
so that your consumers dont need to patch mdsvex

**Comment by vwkd** [comment]
@milahu Thanks you for digging into this and also for fixing the error message in Vite!

I'm thinking it would be a good idea to submit a PR upstream to `remark-parse.markdown`. I have the feeling it will take some time for MDsveX to move to a new parser, so it's waiting either way. Fixing upstream would however be the right thing to do such that MDsveX doesn't need to maintain a custom patch. Also other projects would benefit that may run into the same issue.

**Comment by milahu** [comment]
> Might that be it?

yepp

```console
$ cd MDsveX/packages/mdsvex
$ sed -i 's/sourcemap: false/sourcemap: true/' rollup.config.js
$ npm run build
$ npm i -g source-map-cli
$ source-map resolve dist/main.cjs.js.map 8722 0
Maps to node_modules/parse-entities/index.js:254:0 

        if (namedEntity) {
^
```

thats the problem with fixing upstream:
the code is hidden in some dependency, and we would have to pass our option across all the interfaces

do you have so much time to waste? ; )

**Comment by pngwn** [comment]
I'm not sure an upstream PR would be accepted anyway, I'm pretty sure this is by design from previous conversations I've had. 

I'll Patch this dependency for the short term when I find the time (if anyone wants to submit a PR, I'll happily accept it).
