### ISSUE TITLE
Error when building using a layout file + Tailwind: "ParseError: Semicolon or block is expected"

### ISSUE THREAD

**Issue by Bandit** [pngwn/MDsveX#378]
This layout file fails to build (`Sveltekit 0.9.2`):

```svelte
<script>
    [...]
</script>

<Container class="md md:my-12 md:rounded md:border border-alabaster-dark shadow-xl bg-white">
    {#if heading}
        <header>
            <h1>{heading}</h1>
        </header>
    {/if}
    <section class="py-6 md:py-8 md:px-8">
        <slot />
    </section>
</Container>

<style lang="postcss">
    header {
        @apply bg-cover bg-right py-8 md:rounded-t -mx-6 md:mx-0;
        background: url(/illustrations/mix.png) no-repeat;

        header h1 {
            @apply text-forest-dark text-center;
        }
    }
</style>
```

If I remove the entire `<style>` block then it works. Any ideas?

Config:
```js
const config = {
  "layout": "./src/lib/components/Static.svelte",
  "extensions": [".svelte.md", ".md", ".svx"],

  "smartypants": {
    "dashes": "oldschool"
  },

  "remarkPlugins": [],
  "rehypePlugins": []
};

export default config;
```

Error:
```
Semicolon or block is expected
ParseError: Semicolon or block is expected
    at error ([...]/node_modules/svelte/compiler.js:17706:20)
    at Parser$1.error ([...]/node_modules/svelte/compiler.js:17782:10)
    at Object.read_style [as read] ([...]/node_modules/svelte/compiler.js:14114:21)
    at tag ([...]/node_modules/svelte/compiler.js:16865:34)
    at new Parser$1 ([...]/node_modules/svelte/compiler.js:17741:22)
    at Object.parse$3 [as parse] ([...]/node_modules/svelte/compiler.js:17873:21)
    at process_layouts ([...]/node_modules/mdsvex/dist/main.cjs.js:25908:26)
    at mdsvex ([...]/node_modules/mdsvex/dist/main.cjs.js:26024:12)
    at file:///[...]/svelte.config.js:22:9
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
```

Looks to me like it cannot handle the `@apply` directive. Maybe ignoring the `lang="postcss"` thing?

**Comment by pngwn** [comment]
mdsvex dopes not currently play nicely with preprocessors that add custom syntax. Same issue as https://github.com/pngwn/MDsveX/issues/116
