### ISSUE TITLE
custom highlighter

### ISSUE THREAD

**Issue by rodneylab** [pngwn/MDsveX#379]
Hi, thanks for creating this package, I find it very useful.  I am implementing a custom highlighter for mdsvex fenced code blocks.  In the highlighter function, I wrap the code in a code tag, but it seems it is still being parsed by the compiler. As an example, this works fine:

<pre>
```javascript
console.log('Here!');
```
</pre>

but if I inculde an import in the fenced code block, I get an error message saying that package is not defined:

<pre>
```javascript
import { imagetools } from 'vite-imagetools';
```
</pre>

also if I comment that line out within the code block I get the same thing

<pre>
```javascript
// import { imagetools } from 'vite-imagetools';
```
</pre>

This is the error from these blocks:

<details>
<summary>Click to expand</summary>
imagetools is not defined

ReferenceError: imagetools is not defined
    at index.svelte.md:4:22
    at Object.$$render (/XXX/mdsvex-highlighter/node_modules/.pnpm/svelte@3.44.3/node_modules/svelte/internal/index.js:1702:22)
    at Object.default (root.svelte:38:46)
    at eval (/.svelte-kit/dev/components/layout.svelte:8:41)
    at Object.$$render (/XXX/mdsvex-highlighter/node_modules/.pnpm/svelte@3.44.3/node_modules/svelte/internal/index.js:1702:22)
    at root.svelte:36:44
    at $$render (/XXX/mdsvex-highlighter/node_modules/.pnpm/svelte@3.44.3/node_modules/svelte/internal/index.js:1702:22)
    at Object.render (/XXX/mdsvex-highlighter/node_modules/.pnpm/svelte@3.44.3/node_modules/svelte/internal/index.js:1710:26)
    at render_response (file:///Users/XXX/mdsvex-highlighter/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.202_svelte@3.44.3/node_modules/@sveltejs/kit/dist/ssr.js:561:28)
    at async respond$1 (file:///XXX/mdsvex-highlighter/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.202_svelte@3.44.3/node_modules/@sveltejs/kit/dist/ssr.js:1377:4)
</details>

I use the following config:

```javascript
import adapter from '@sveltejs/adapter-auto';
import { mdsvex } from 'mdsvex';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	extensions: ['.svelte', '.svelte.md', '.md', '.mdx', '.svx'],
	preprocess: [
    mdsvex({
      extensions: ['.svelte.md', '.md', '.mdx', '.svx'],
      highlight: {
        highlighter: (code, language) => `<pre><code class="${language}">${code}</code></pre>`,
      },
    }),
  ],
	kit: {
		adapter: adapter(),

		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte'
	}
};

export default config;
```
I created a minimal [replication.](https://github.com/rodneylab/mdsvex-highlighter)

I have the following versions:
@sveltejs/kit
: 1.0.0-next.202

mdsvex
: 0.9.8

svelte:
: 3.44.0

node
: 16.13.1

Please let me know if you need more details.  Happy to help with fix.

**Comment by pngwn** [comment]
This is working as intended. If you use a custom highlighter you will need to escape curly braces `{` and `}` as the svelte compiler will interpret them as template expressions.
