### ISSUE TITLE
Latest release failing on build `one$6 is not a function`

### ISSUE THREAD

**Issue by spences10** [pngwn/MDsveX#406]
Latest release is breaking on build: `mdsvex v0.10.2`

Here's the build output:

<details>
	<summary>Build output</summary>
> svelte-kit build

vite v2.7.13 building for production...
✓ 35 modules transformed.
[vite-plugin-svelte] Error while preprocessing /home/scott/repos/personal/scottspence.com/copy/about.md - one$6 is not a function
file: /home/scott/repos/personal/scottspence.com/copy/about.md
> Error while preprocessing /home/scott/repos/personal/scottspence.com/copy/about.md - one$6 is not a function
    at all$h (/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/mdsvex@0.10.2_svelte@3.46.3/node_modules/mdsvex/dist/main.cjs.js:12187:14)
    at root (/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/mdsvex@0.10.2_svelte@3.46.3/node_modules/mdsvex/dist/main.cjs.js:12877:45)
    at one$5 (/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/mdsvex@0.10.2_svelte@3.46.3/node_modules/mdsvex/dist/main.cjs.js:12235:51)
    at toHast (/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/mdsvex@0.10.2_svelte@3.46.3/node_modules/mdsvex/dist/main.cjs.js:13101:14)
    at transformer (/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/mdsvex@0.10.2_svelte@3.46.3/node_modules/mdsvex/dist/main.cjs.js:13151:12)
    at wrapped (/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/mdsvex@0.10.2_svelte@3.46.3/node_modules/mdsvex/dist/main.cjs.js:197:19)
    at next (/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/mdsvex@0.10.2_svelte@3.46.3/node_modules/mdsvex/dist/main.cjs.js:292:26)
    at done (/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/mdsvex@0.10.2_svelte@3.46.3/node_modules/mdsvex/dist/main.cjs.js:227:16)
    at then (/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/mdsvex@0.10.2_svelte@3.46.3/node_modules/mdsvex/dist/main.cjs.js:234:5)
[!] Error: unfinished hook action(s) on exit:
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/components/head.svelte"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/components/landing-hero.svelte"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/components/people-to-meet.svelte"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/info.js"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/og-image-url-build.js"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/copy/privacy-policy.md"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/copy/newsletter.md"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/components/newsletter-signup.svelte"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/copy/portfolio.md"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/copy/speaking-2019.md"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/copy/speaking-2020.md"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/copy/speaking-2021.md"
(vite:css) transform "/home/scott/repos/personal/scottspence.com/src/app.css"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/copy/speaking.md"
(vite:css) transform "/home/scott/repos/personal/scottspence.com/src/prism.css"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/components/date-updated.svelte"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/components/small.svelte"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/fuse.js@6.5.3/node_modules/fuse.js/dist/fuse.esm.js"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/get-posts.js"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/components/post-card.svelte"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/node_modules/.pnpm/date-fns@2.28.0/node_modules/date-fns/esm/index.js"
(vite:load-fallback) load "/home/scott/repos/personal/scottspence.com/src/lib/components/butt-butt.svelte"

 ELIFECYCLE  Command failed with exit code 1.
</details>

**Comment by pngwn** [comment]
Reverted the recent changes and released a new version. I haven't tested it yet but let me know how that works for you. `0.10.3`.

**Comment by pngwn** [comment]
It didn't work. Next one will.

**Comment by pngwn** [comment]
Maybe.

**Comment by pngwn** [comment]
It did.

Fixed in `0.10.4`.
