### ISSUE TITLE
Custom frontmatter with dashes breaks MDsveX

### ISSUE THREAD

**Issue by kangruixiang** [pngwn/MDsveX#472]
Having custom frontmatter with dashes will cause errors. 

Example frontmatter:

```
---
date: 2022-02-05
sr-due: 2022-07-20
sr-interval: 4
sr-ease: 270
---
```

Error message: 

```
 1 |  <script context="module">
 2 |    export const metadata = {"date":"2022-02-05T00:00:00.000Z","sr-due":"2022-07-20T00:00:00.000Z","sr-interval":4,"sr-ease":270};
 3 |    const { date, sr-due, sr-interval, sr-ease } = metadata;
                        ^
 4 |  </script>
```

I've also tried changing the config file:

```
frontmatter: {
		parse(frontmatter, messages) {
			try {
				let fm = load(frontmatter.replace(/-/g, ''));
				return toml.parse(fm);
			} catch (e) {
				messages.push(e.message);
			}
		}
	}
```

This gives the following error:

```
Cannot read properties of undefined (reading 'open')
TypeError: Error while preprocessing D:/Git/my-wiki/src/routes/test/1.md - Cannot read properties of undefined (reading 'open')
    at pick (D:\Git\my-wiki\node_modules\mdsvex\dist\main.cjs.js:14170:54)
    at fence (D:\Git\my-wiki\node_modules\mdsvex\dist\main.cjs.js:14166:10)
    at create$2 (D:\Git\my-wiki\node_modules\mdsvex\dist\main.cjs.js:14177:14)
    at wrap$1 (D:\Git\my-wiki\node_modules\mdsvex\dist\main.cjs.js:14274:13)
    at attachParser (D:\Git\my-wiki\node_modules\mdsvex\dist\main.cjs.js:14250:20)
    at Function.frontmatter (D:\Git\my-wiki\node_modules\mdsvex\dist\main.cjs.js:14240:5)
    at freeze (D:\Git\my-wiki\node_modules\mdsvex\dist\main.cjs.js:799:28)
    at Function.process (D:\Git\my-wiki\node_modules\mdsvex\dist\main.cjs.js:1029:5)
    at markup (D:\Git\my-wiki\node_modules\mdsvex\dist\main.cjs.js:26045:32)
    at process_markup (file:///D:/Git/my-wiki/node_modules/svelte/compiler.mjs:43249:29)
```

**Comment by nosovk** [comment]
Frontmatter key converted to field name in metadata object. If key name is not valid in terms of js - compilation will fail.
Probably this is the reason, but better check
