### ISSUE TITLE
`import`ed mdsvex file throws error with sveltekit but returns content just fine

### ISSUE THREAD

**Issue by JaKXz** [pngwn/MDsveX#499]
Hi, I'm using [this starter](https://github.com/josh-collinsworth/sveltekit-blog-starter) and wanted to (try) just import(ing) the html output of a file and putting that directly into my component. However, when I try to write something like this in my load function (using `+layout.js` in this example):

```js
export async function load({ url }) {
	const readme = await import('../../README.md').then((mod) => mod.default.render().html);
```

this error is thrown:

```
TypeError: mod.default.render is not a function
    at +layout.js:4:77
    at async load (+layout.js:4:17)
    at async load_node (client.js?v=a845393a:682:14)
    at async Promise.all (:5173/index 0)
    at async Object._hydrate (client.js?v=a845393a:1762:14)
    at async Module.start (start.js:22:3)
```

What's interesting is that if I simply ignore the error the content shows up fine in the component, and can be rendered in a fragment like so:

```svelte
<svelte:fragment slot="attribution">
	{@html data.readme}
</svelte:fragment>
```

I'm curious if I should just _not do this_ for some reason or if I've found an actual bug or if I can safely ignore the error? Sorry if this is a duplicated issue, I couldn't find anything based on a cursory search.

**Comment by WilliamDiakite** [comment]
Same here.
@JaKXz, have you found a solution to your problem?

**Comment by JaKXz** [comment]
I have not unfortunately.

**Comment by pngwn** [comment]
Hmmm. I wonder if this is a type issue. I'll see if I can reproduce.

**Comment by ghostdevv** [comment]
It's because you're using a load function that runs both on server & client - on the server it generates a ssr component which has `.render` but on the client it generates a client component which does not

I'd suggest that instead you use `<svelte:component this={...} />` rather than rendering like that, or if you do just want to send back html use a `+layout.server.ts`/`+page.server.ts`

**Comment by JaKXz** [comment]
That makes a lot of sense, thanks @ghostdevv! @pngwn I'll close this for now, feel free to reopen if you want to use it to track work on something.
