### ISSUE TITLE
NPM warning from Svelte v4 peer dependency

### ISSUE THREAD

**Issue by janosh** [pngwn/MDsveX#518]
I've encountered no issues using mdsvex with the [Svelte v4 pre-release](https://github.com/sveltejs/svelte/releases/tag/svelte%404.0.0-next.1). Would be nice to get rid of this NPM warning:

```diff
 WARN  Issues with peer dependencies found
.
  ├─┬ @sveltejs/package 2.0.2
  │ └── ✕ unmet peer svelte@^3.44.0: found 4.0.0-next.2
  ├─┬ eslint-plugin-svelte3 4.0.0
  │ └── ✕ unmet peer svelte@^3.2.0: found 4.0.0-next.2
+ └─┬ mdsvex 0.10.6
+   └── ✕ unmet peer svelte@3.x: found 4.0.0-next.2
```

**Comment by anzbert** [comment]
yes please update the dependency to the new svelte 4.0 :)

thx !!

**Comment by nerometa** [comment]
Also encountered this issue. I generated my SvelteKit project with pnpm.

This is my package.json:

```json
"devDependencies": {
  "@sveltejs/adapter-auto": "^2.0.0",
  "@sveltejs/kit": "^1.20.4",
  "@typescript-eslint/eslint-plugin": "^5.45.0",
  "@typescript-eslint/parser": "^5.45.0",
  "eslint": "^8.28.0",
  "eslint-config-prettier": "^8.5.0",
  "eslint-plugin-svelte": "^2.30.0",
  "mdsvex": "^0.10.6",
  "prettier": "^2.8.0",
  "prettier-plugin-svelte": "^2.10.1",
  "sass": "^1.63.6",
  "svelte": "^4.0.0",
  "svelte-check": "^3.4.3",
  "svelte-preprocess": "^5.0.4",
  "tslib": "^2.4.1",
  "typescript": "^5.0.0",
  "vite": "^4.3.6"
}
```

My Config:

```js
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/kit/vite';
import { mdsvex } from 'mdsvex';

/** @type {import('mdsvex').MdsvexOptions} */
const mdsvexOptions = {
	extension: ['.md']
};

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://kit.svelte.dev/docs/integrations#preprocessors
	// for more information about preprocessors
	extensions: ['.svelte', '.md'],
	preprocess: [vitePreprocess(), mdsvex(mdsvexOptions)],

	kit: {
		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
		adapter: adapter()
	}
};

export default config;

```

And this is the error it gives:

```
10:06:26 PM [vite] Error when evaluating SSR module /node_modules/.pnpm/@sveltejs+kit@1.20.5_svelte@4.0.0_vite@4.3.9/node_modules/@sveltejs/kit/src/runtime/server/index.js: failed to import "/.svelte-kit/generated/server/internal.js"
|- TypeError: Error while preprocessing /home/verdilaq/Documents/VSCodium/nerometa-blog/.svelte-kit/generated/root.svelte - ext.split is not a function
    at /home/verdilaq/Documents/VSCodium/nerometa-blog/node_modules/.pnpm/mdsvex@0.10.6_svelte@4.0.0/node_modules/mdsvex/dist/main.cjs.js:26041:9
    at Array.map (<anonymous>)
    at markup (/home/verdilaq/Documents/VSCodium/nerometa-blog/node_modules/.pnpm/mdsvex@0.10.6_svelte@4.0.0/node_modules/mdsvex/dist/main.cjs.js:26040:56)
    at process_markup (file:///home/verdilaq/Documents/VSCodium/nerometa-blog/node_modules/.pnpm/svelte@4.0.0/node_modules/svelte/src/compiler/preprocess/index.js:309:26)
    at preprocess (file:///home/verdilaq/Documents/VSCodium/nerometa-blog/node_modules/.pnpm/svelte@4.0.0/node_modules/svelte/src/compiler/preprocess/index.js:355:31)
    at async compileSvelte (file:///home/verdilaq/Documents/VSCodium/nerometa-blog/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@2.4.2_svelte@4.0.0_vite@4.3.9/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.js:89:20)
    at async TransformContext.transform (file:///home/verdilaq/Documents/VSCodium/nerometa-blog/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@2.4.2_svelte@4.0.0_vite@4.3.9/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:220:20)
    at async Object.transform (file:///home/verdilaq/Documents/VSCodium/nerometa-blog/node_modules/.pnpm/vite@4.3.9_sass@1.63.6/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42919:30)
    at async loadAndTransform (file:///home/verdilaq/Documents/VSCodium/nerometa-blog/node_modules/.pnpm/vite@4.3.9_sass@1.63.6/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53385:29)
```

**Comment by pngwn** [comment]
I'll get this all sorted this weekend.
