### ISSUE TITLE
Weird parse error (Unexpected token) with svelte 4.0.4, mdsvex v0.11.0

### ISSUE THREAD

**Issue by abraithwaite** [pngwn/MDsveX#526]
Following this blog, but with typescript instead of vanilla JS.

I'm not a JS / TS / frontend guy so forgive me if I don't provide enough details.  Let me know what else I can do.

Below is the error / stacktrace.  Looks like it's coming from parse in `svelte/compiler` at this line:

https://github.com/pngwn/MDsveX/blob/26591be63e088f57c78108553813ef18cc8ca5b1/packages/mdsvex/src/index.ts#L158

```
error when starting dev server:
Error: Unexpected token (2:17)
1: <script lang="ts">
2:   export let title: string;
                     ^
3:   export let date: Date;
4: </script>
        at /Users/abraithwaite/Projects/gitlab.com/abraithwaite/svblog/src/lib/components/Post.svelte
    at process_layouts (/Users/abraithwaite/Projects/gitlab.com/abraithwaite/svblog/node_modules/mdsvex/dist/main.cjs.js:25910:10)
    at mdsvex (/Users/abraithwaite/Projects/gitlab.com/abraithwaite/svblog/node_modules/mdsvex/dist/main.cjs.js:26027:12)
    at file:///Users/abraithwaite/Projects/gitlab.com/abraithwaite/svblog/svelte.config.js?ts=1688535493940:15:3
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:246:24)
    at async load_config (file:///Users/abraithwaite/Projects/gitlab.com/abraithwaite/svblog/node_modules/@sveltejs/kit/src/core/config/index.js:70:17)
    at async sveltekit (file:///Users/abraithwaite/Projects/gitlab.com/abraithwaite/svblog/node_modules/@sveltejs/kit/src/exports/vite/index.js:119:24)
    at async Promise.all (index 0)
    at async asyncFlatten (file:///Users/abraithwaite/Projects/gitlab.com/abraithwaite/svblog/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:12623:16)
    at async resolveConfig (file:///Users/abraithwaite/Projects/gitlab.com/abraithwaite/svblog/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64022:29)
```

**Comment by abraithwaite** [comment]
Here's the repo & file for reproducing, if possible:

https://gitlab.com/abraithwaite/svblog/-/blob/main/src/lib/components/Post.svelte

I know that repo is very messy, just a few hours after create-svelte with sveltekit following that blog I linked.

**Comment by abraithwaite** [comment]
Looks like https://github.com/sveltejs/svelte/issues/8916 is not a priority for the Svelte team, so I'll probably just do the JSDoc workaround for now.  I understand that this project is not supported by a large team.  Hopefully someone comes across this and immediately knows what the issue is.

Thanks for the great lib @pngwn!

**Comment by dominikg** [comment]
duplicate of https://github.com/pngwn/MDsveX/issues/116

**Comment by pngwn** [comment]
Thanks @dominikg. Closing as dupe.
