### ISSUE TITLE
Directly preprocess: docs example doesn't work

### ISSUE THREAD

**Issue by jerrygreen** [pngwn/MDsveX#542]
mdsvex docs say:

> If you want to use mdsvex without a bundler because you are your own person, then you can use svelte.preprocess directly:
> 
> ```javascript
> // This will give you a valid svelte component
> const preprocessed = await svelte.preprocess(
>   source,
>   mdsvex(mdsvex_opts)
> );
> ```
>  https://mdsvex.com/docs

But as you can see, it doesn't work:

![image](https://github.com/pngwn/MDsveX/assets/13215662/3947570b-75c6-4e6c-a134-d26c5b63ced7)

More in-depth details:

- `svete.preprocess` expects `PreprocessorGroup | PreprocessorGroup[]`
- mdsvex returens not a group but just `Preprocesssor`

![image](https://github.com/pngwn/MDsveX/assets/13215662/92434171-e270-46f5-b1ef-918346471764)

Of course it's not just typing system is wrong, at runtime I'm getting error:

```
TypeError: Cannot read properties of undefined (reading 'split')
    at markup (.../node_modules/mdsvex/dist/main.cjs.js:26044:43)
```

I'm using everything latest at the current moment:

- `mdsvex`: 0.11.0
- `svelte`: 4.2.0
- `@sveltejs/kit`: 1.24.1

I tried a couple older versions of svelte to find those are compatible, but no luck finding them.

**Comment by conner-replogle** [comment]
Have you figured it out because I am having the same issue.

**Comment by jerrygreen** [comment]
I ended up not using mdsvex, and instead I use remark+rehype+unified, and a bunch of plugins

It’s not the same but fits my needs

**Comment by shot-codes** [comment]
I am also seeing this and would and would love to hear if there is a way to use it manually in some way.

**Comment by lemoncove** [comment]
I've found that you can mitigate the type errors like so:

```ts
const processed = await svelte.preprocess(
    source,
    {
        name: "mdsvex",
        markup: (options: { content: string, filename?: string }) => {
            const args = {
                content: options.content,
                filename: options.filename || "unknown.svx",
            };

            return mdsvex().markup(args);
        }
    }
);
```

I'm not certain if this is a faux-pas because I'm not really sure what `filename` is used for, but in any case this still yields a runtime error:

```
TypeError: source.split is not a function
    at getLocator (file:///C:/Users/lemon/test/node_modules/.pnpm/locate-character@3.0.0/node_modules/locate-character/src/index.js:19:24)
    at PreprocessResult.update_source (C:\Users\lemon\test\node_modules\.pnpm\svelte@5.28.2\node_modules\svelte\src\compiler\preprocess\index.js:70:34)
    at new PreprocessResult (C:\Users\lemon\test\node_modules\.pnpm\svelte@5.28.2\node_modules\svelte\src\compiler\preprocess\index.js:59:8)
    at preprocess (C:\Users\lemon\test\node_modules\.pnpm\svelte@5.28.2\node_modules\svelte\src\compiler\preprocess\index.js:348:17)
    at load (C:\Users\lemon\test\src\routes\[slug]\+page.server.ts:12:29)
    at async load_server_data (C:\Users\lemon\test\node_modules\.pnpm\@sveltejs+kit@2.20.8_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.28.2_vite@6.3.5_sass-embedde_ycrt4dhi5gsomrskzzcpgtme4a\node_modules\@sveltejs\kit\src\runtime\server\page\load_data.js:70:17)
    at async eval (C:\Users\lemon\test\node_modules\.pnpm\@sveltejs+kit@2.20.8_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.28.2_vite@6.3.5_sass-embedde_ycrt4dhi5gsomrskzzcpgtme4a\node_modules\@sveltejs\kit\src\runtime\server\page\index.js:157:13)
```
