### ISSUE TITLE
bug: ext.startsWith is not a function

### ISSUE THREAD

**Issue by midirhee12** [pngwn/MDsveX#681]
After adding this to the `svelte.config.js`:
```js
    mdsvex({
      extension: [".md", ".svx"],
    }),
```

I get the following:
```
TypeError: Error while preprocessing /home/midirhee12/Projects/midirhee12/personal-website/main/.svelte-kit/generated/root.svelte - ext.startsWith is not a function
    at /home/midirhee12/Projects/midirhee12/personal-website/main/node_modules/.pnpm/mdsvex@0.11.2_svelte@5.14.4/node_modules/mdsvex/dist/main.cjs.js:24416:71
    at Array.map (<anonymous>)
    at markup (/home/midirhee12/Projects/midirhee12/personal-website/main/node_modules/.pnpm/mdsvex@0.11.2_svelte@5.14.4/node_modules/mdsvex/dist/main.cjs.js:24416:56)
    at process_markup (file:///home/midirhee12/Projects/midirhee12/personal-website/main/node_modules/.pnpm/svelte@5.14.4/node_modules/svelte/src/compiler/preprocess/index.js:309:26)
    at Module.preprocess (file:///home/midirhee12/Projects/midirhee12/personal-website/main/node_modules/.pnpm/svelte@5.14.4/node_modules/svelte/src/compiler/preprocess/index.js:355:31)
    at async compileSvelte (file:///home/midirhee12/Projects/midirhee12/personal-website/main/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@4.0.4_svelte@5.14.4_vite@5.4.11_@types+node@18.19.68_/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.js:85:20)
    at async TransformPluginContext.transform (file:///home/midirhee12/Projects/midirhee12/personal-website/main/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@4.0.4_svelte@5.14.4_vite@5.4.11_@types+node@18.19.68_/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:148:20)
    at async PluginContainer.transform (file:///home/midirhee12/Projects/midirhee12/personal-website/main/node_modules/.pnpm/vite@5.4.11_@types+node@18.19.68/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49096:18)
    at async loadAndTransform (file:///home/midirhee12/Projects/midirhee12/personal-website/main/node_modules/.pnpm/vite@5.4.11_@types+node@18.19.68/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51929:27)
    at async instantiateModule (file:///home/midirhee12/Projects/midirhee12/personal-website/main/node_modules/.pnpm/vite@5.4.11_@types+node@18.19.68/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52874:44)
```

Seems to be related to: https://github.com/pngwn/MDsveX/blob/f29f31c281c93a1f5e604ccc9f8e4cc14208a8d8/packages/mdsvex/src/index.ts#L293

**Comment by HannesT117** [comment]
Hi @midirhee12 I just had the same issue - there is both `extension` and `extensions` available. The first is deprecated and can only work with a (single) string. The latter (`extensions`) is the way to go if you want to pass an array :)
